// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Praktikum.Services.Data;

#nullable disable

namespace Praktikum.Services.Migrations.KostenstelleDb
{
    [DbContext(typeof(KostenstelleDbContext))]
    [Migration("20250722072803_AddKostenstellezeile")]
    partial class AddKostenstellezeile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Praktikum.Types.Kostenstellezeile", b =>
                {
                    b.Property<int>("KostenstellezeileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KostenstellezeileId"));

                    b.Property<string>("KostenstelleBeschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KostenstelleOrt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KostenstellezeileId");

                    b.ToTable("Kostenstelle");
                });
#pragma warning restore 612, 618
        }
    }
}
