// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Praktikum.Services.Data;

#nullable disable

namespace Praktikum.Services.Migrations.KategorieDb
{
    [DbContext(typeof(KategorieDbContext))]
    [Migration("20250722072901_AddKategoriezeile")]
    partial class AddKategoriezeile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Praktikum.Types.Kategoriezeile", b =>
                {
                    b.Property<int>("KategoriezeileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriezeileId"));

                    b.Property<string>("KategorieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategorieNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriezeileId");

                    b.ToTable("Kategorie");
                });
#pragma warning restore 612, 618
        }
    }
}
