// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Praktikum.Services.Data;

#nullable disable

namespace Praktikum.Services.Migrations.SteuersatzDb
{
    [DbContext(typeof(SteuersatzDbContext))]
    partial class SteuersatzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Praktikum.Types.Steuersatzzeile", b =>
                {
                    b.Property<int>("SteuersatzzeileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SteuersatzzeileId"));

                    b.Property<int>("Prozentsatz")
                        .HasColumnType("int");

                    b.Property<string>("SteuersatzInProzent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SteuersatzzeileId");

                    b.ToTable("Steuersatz");
                });
#pragma warning restore 612, 618
        }
    }
}
